server:
  port: 8080
spring:
  application:
    name: cp-demo-fe
  datasource:
    platform: postgres
    url: jdbc:postgresql://host.docker.internal:5432/ceska_posta?currentSchema=digi_hub
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    batch:
      initialize-schema: never
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    cz.cp.digihub: DEBUG
